<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="theanh" failures="4" tests="20" name="testNG" time="0.237" errors="0" timestamp="2025-04-04T14:16:46 ICT">
  <testcase classname="poly.java5.test.SearchTest" name="testSearch_Fail" time="0.025"/>
  <testcase classname="poly.java5.test.CartTest" name="testAddCart_Fail_ExceedStock" time="0.026"/>
  <testcase classname="poly.java5.test.OrderTest" name="testOrder_Fail_EmptyCart" time="0.026"/>
  <testcase classname="poly.java5.test.LoginTest" name="testFindByUsernameAndPassword_Failure_BothInvalid" time="0.024"/>
  <testcase classname="poly.java5.test.RegisterTest" name="testRegister_Fail_EmailExists" time="0.024"/>
  <testcase classname="poly.java5.test.CartTest" name="testAddCart_Success" time="0.006"/>
  <testcase classname="poly.java5.test.LoginTest" name="testFindByUsernameAndPassword_Failure_InvalidPassword" time="0.006"/>
  <testcase classname="poly.java5.test.SearchTest" name="testSearch_Success" time="0.009"/>
  <testcase classname="poly.java5.test.CartTest" name="testAddCart_Success_ExistingProduct" time="0.004"/>
  <testcase classname="poly.java5.test.RegisterTest" name="testRegister_Fail_InvalidEmailFormat" time="0.01"/>
  <testcase classname="poly.java5.test.LoginTest" name="testFindByUsernameAndPassword_Failure_InvalidUsername" time="0.002"/>
  <testcase classname="poly.java5.test.CartTest" name="testDeleteCart_Success" time="0.003"/>
  <testcase classname="poly.java5.test.RegisterTest" name="testRegister_Fail_InvalidPassword" time="0.002"/>
  <testcase classname="poly.java5.test.CartTest" name="testUpdateCart_Fail_UpdateToZero" time="0.001"/>
  <testcase classname="poly.java5.test.RegisterTest" name="testRegister_Success" time="0.003"/>
  <testcase classname="poly.java5.test.LoginTest" name="testFindByUsernameAndPassword_Success" time="0.008"/>
  <testcase classname="poly.java5.test.OrderTest" name="testOrder_Fail_InvalidEmail" time="0.035">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Vui lòng điền đúng email&amp;gt; but was: &amp;lt;Giỏ hàng trống, hãy mua sắm thêm&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Vui lòng điền đúng email> but was: <Giỏ hàng trống, hãy mua sắm thêm>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at poly.java5.test.OrderTest.testOrder_Fail_InvalidEmail(OrderTest.java:33)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testOrder_Fail_InvalidEmail -->
  <testcase classname="poly.java5.test.OrderTest" name="testOrder_Fail_InvalidPhoneNumber" time="0.002">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Vui lòng điền đúng SĐT&amp;gt; but was: &amp;lt;Giỏ hàng trống, hãy mua sắm thêm&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Vui lòng điền đúng SĐT> but was: <Giỏ hàng trống, hãy mua sắm thêm>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at poly.java5.test.OrderTest.testOrder_Fail_InvalidPhoneNumber(OrderTest.java:40)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testOrder_Fail_InvalidPhoneNumber -->
  <testcase classname="poly.java5.test.OrderTest" name="testOrder_Fail_NoPaymentMethod" time="0.002">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Hãy chọn phương thức thanh toán&amp;gt; but was: &amp;lt;Giỏ hàng trống, hãy mua sắm thêm&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Hãy chọn phương thức thanh toán> but was: <Giỏ hàng trống, hãy mua sắm thêm>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at poly.java5.test.OrderTest.testOrder_Fail_NoPaymentMethod(OrderTest.java:54)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testOrder_Fail_NoPaymentMethod -->
  <testcase classname="poly.java5.test.OrderTest" name="testOrder_Success" time="0.001">
    <failure type="org.opentest4j.AssertionFailedError" message="expected: &amp;lt;Đặt thành công&amp;gt; but was: &amp;lt;Giỏ hàng trống, hãy mua sắm thêm&amp;gt;">
      <![CDATA[org.opentest4j.AssertionFailedError: expected: <Đặt thành công> but was: <Giỏ hàng trống, hãy mua sắm thêm>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at poly.java5.test.OrderTest.testOrder_Success(OrderTest.java:26)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testOrder_Success -->
</testsuite> <!-- testNG -->
